### ISSUE TITLE
Something wrong in initial_selection.py

### ISSUE THREAD

**Issue by ffhibnese** [LukasStruppek/Plug-and-Play-Attacks#10]
Hello, Lukas

Thanks for your great contribution to the model inversion community!

When I read the source code of the function `find_initial_w` in initial_selection.py, I found something confusing about the variable `imgs`.

The resize option somehow transforms the `imgs` to list type, so the following for loop actually calculates the target confidence of **a batch**. However, the subsequent operation seems to select the vectors of **a single image** with higher confidence, which is contradictory with the former calculation of confidences.

Is there any mistake in my understanding? 
I would like to appreciate it if you could help me out

**Comment by LukasStruppek** [comment]
Hey,

thank you for your interest in our work. I am currently quite busy, but I will try to look into the problem within the current week and get back to you.

Best,
Lukas

**Comment by LukasStruppek** [comment]
Hey,

I just checked the code. The transformation of the images into a list is required for the horizontal Flip operation [(line 74).](https://github.com/LukasStruppek/Plug-and-Play-Attacks/blob/d24c1387acce8f6db7ac808b6fd0eca57b52d6b6/attacks/initial_selection.py#L74). So we can compute the target model's confidence on each image and its flipped version. Similarly, when using the five_crop augmentation ([line 78](https://github.com/LukasStruppek/Plug-and-Play-Attacks/blob/d24c1387acce8f6db7ac808b6fd0eca57b52d6b6/attacks/initial_selection.py#L78)) a list of crops is returned. To make all those operations compatible to each other, we already put the images into a list after the resizing operation.

We then iterate over all augmented version of the batches ([line 82](https://github.com/LukasStruppek/Plug-and-Play-Attacks/blob/d24c1387acce8f6db7ac808b6fd0eca57b52d6b6/attacks/initial_selection.py#L82)) and compute the average prediction score for each class by adding up all prediction confidences divided by the number of augmented image versions (the number of elements in the imgs list).

Finally, we select the top-k (200 in the default implementation) latents that achieve the highest initial prediction score on the target model [line 90](https://github.com/LukasStruppek/Plug-and-Play-Attacks/blob/d24c1387acce8f6db7ac808b6fd0eca57b52d6b6/attacks/initial_selection.py#L90).

I hope this answers your question. If not, I am happy to provide more details.

Best,
Lukas

**Comment by ffhibnese** [comment]
Thanks for your careful reply!

I absolutely understand the analysis and let me express my puzzle more clearly.

After `imgs` was transformed into a list, the for loop in [line 82](https://github.com/LukasStruppek/Plug-and-Play-Attacks/blob/d24c1387acce8f6db7ac808b6fd0eca57b52d6b6/attacks/initial_selection.py#L82) actually calculates the confidence of **each batch** since the `imgs` becomes a list with two elements (i.e., the initial batch of `imgs` and its hflip version).

However,  the [line 93](https://github.com/LukasStruppek/Plug-and-Play-Attacks/blob/d24c1387acce8f6db7ac808b6fd0eca57b52d6b6/attacks/initial_selection.py#L93) seems to select a single **image** according to the confidence computed by a **batch**， which is not reasonable.

**Comment by LukasStruppek** [comment]
Ah, I see. Yes, it indeed selects only a single image. But in Line 96, the confidence of the current sample is set to -1. And the list of targets not only includes [0, 1, 2, ...] but each target is contained k times, i.e., [0, 0, 0,..., 1, 1, 1,...]. Therefore, the loop assigns to each individual target a single different latent vector.

Best,
Lukas

**Comment by ffhibnese** [comment]
> Ah, I see. Yes, it indeed selects only a single image. But in Line 96, the confidence of the current sample is set to -1. And the list of targets not only includes [0, 1, 2, ...] but each target is contained k times, i.e., [0, 0, 0,..., 1, 1, 1,...]. Therefore, the loop assigns to each individual target a single different latent vector.
> 
> Best, Lukas

Thanks for your reply!

My key point is that how could you select a image by the confidence of a batch, rather than the confidence of the image itself.

**Comment by LukasStruppek** [comment]
We do not select the image directly but its underlying latent vector. And the confidence of the batch is the mean confidence of the images generated with the same latent vector but transformed by random augmentations. So we compute the mean confidence for each latent vector by taking the mean confidence for different augmented variations of the corresponding generated images.

**Comment by ffhibnese** [comment]
But in [line57](https://github.com/LukasStruppek/Plug-and-Play-Attacks/blob/d24c1387acce8f6db7ac808b6fd0eca57b52d6b6/attacks/initial_selection.py#L57C49-L57C49), the dataloader returns 25 latent vectors at every iteration, so the calculated confidence is the average of the 25 images and its hlip version. And later you select a single latent vector by the average confidence of 25 imgs.

**Comment by ffhibnese** [comment]
> We do not select the image directly but its underlying latent vector. And the confidence of the batch is the mean confidence of the images generated with the same latent vector but transformed by random augmentations. So we compute the mean confidence for each latent vector by taking the mean confidence for different augmented variations of the corresponding generated images.

I‘ve figured everything out.  My puzzle comes from the misunderstanding about the output confidence of a model for a batch of data. 
Quite sorry for disturbing you for several days, Lukas. The code is definitely correct and thanks again for your careful reply and thoughtful analysis!
