### ISSUE TITLE
The provided pretrained file could not match with the corresponding model structure.

### ISSUE THREAD

**Issue by ffhibnese** [LukasStruppek/Plug-and-Play-Attacks#11]
Hi Lukas

I downloaded the `resnest101_celeba.pt` file released in v1 but failed to load it as `resnet101` with the following code.
``` python
        T= resnet.resnet101(1000)
        path_T = os.path.join(ckpt_dir, 'resnest101_celeba.pt')
        T = (T).to(device)
        ckp_T = torch.load(path_T, map_location=device)['model_state_dict']
        T.load_state_dict(ckp_T)
        T.eval()
```
And it raises a KeyError: 'model_state_dict'.
Then I delete the `model_state_dict`:
```
        T= resnet.resnet101(1000)
        path_T = os.path.join(ckpt_dir, 'resnest101_celeba.pt')
        T = (T).to(device)
        ckp_T = torch.load(path_T, map_location=device)
        T.load_state_dict(ckp_T)
        T.eval()
```
But it continues to raise errors like:
![image](https://github.com/LukasStruppek/Plug-and-Play-Attacks/assets/91327274/e3073b7d-909f-4ebb-92da-af56a41a20bc)
My torch version is '1.13.1' and Python is '3.8'.
Could you please tell me the exact model file you used to train the `resnet101`?

**Comment by LukasStruppek** [comment]
Hey,

I just took a look at your problem and fortunately, it is easy to fix :)

To load the model, simply use the following code:
```
import torch
from models.classifier import Classifier
T = Classifier(num_classes=1000, architecture='resnest101').cuda()
T.load_state_dict(torch.load('resnest101_celeba.pt'))
```

There are two small errors in your code snippet. First, use the Classifier class to define the model architecture and second, it is a ResNeSt-101 and not a ResNet-101. That is why the keys do not match. If you want to use a ResNet, there are also weights for the ResNet-152 available. Or you can simply train a new model with the provided training script, you simply have to change the model architecture there.

I hope this solves the problem.

Best,
Lukas

**Comment by ffhibnese** [comment]
My problem was perfectly solved by your suggestion!
