### ISSUE TITLE
Pretrained models for Table 1 in the PPA paper

### ISSUE THREAD

**Issue by final-solution** [LukasStruppek/Plug-and-Play-Attacks#12]
Hi Lukas,

Your method have been truly enlightening and have inspired our team to delve deeper into the methodologies and results you've shared.

We would greatly appreciate it if you could provide us with the pretrained StyleGAN2 model utilized in Table 1, which is pretrained by yourself. If possible, could you please share with us the detailed settings for launching the VMI's Gaussian method?

Thank you very much!

**Comment by LukasStruppek** [comment]
Dear Yixiang,

I am very happy that you like our research :)

Regarding the StyleGAN model: Unfortunately, I no longer have the model weights for this particular StyleGAN. However, we simply used the official training script provided in the Nvidia Repo (https://github.com/NVlabs/stylegan2-ada-pytorch) to train the model. You can also find additional pre-trained models with different resolutions at https://catalog.ngc.nvidia.com/orgs/nvidia/teams/research/models/stylegan2/files. If you want to train a StyleGAN by yourself, you can use the hyperparameters which we specified in Appx. B.6 in the paper. 

For VMI, we also specify the parameters in B.6. However, I recall that getting the official VMI code running was a bit tricky. I, therefore, directly contacted the author by mail to get some help with the code. I think he updated the repo to add all required files.

If you have any additional questions, feel free to reach out to me.

Best,
Lukas

**Comment by final-solution** [comment]
Thanks for your careful reply and suggestions! I will try to contact the author of VMI.

**Comment by final-solution** [comment]
Could you share more parameters for launching VMI with Gaussian approach? For instance, the number of GMM models and the iteration times for each epoch are not stated in Appx. B.6.

**Comment by LukasStruppek** [comment]
Hey,

sorry for the late response — I was on vacation on the last weeks.

Regarding the hyperparameters, I do not exactly recall them. However, I think I used the default parameters provided in the VMI scripts or the paper. I remember that the experiments took quite some time, much longer than any other type of attack.

Best,
Lukas
