### ISSUE TITLE
BigGAN for FFHQ dataset

### ISSUE THREAD

**Issue by 15949659678** [LukasStruppek/Plug-and-Play-Attacks#6]
Hi Lukas, thanks for this interesting paper,I think your article is great and has inspired me a lot.
I am interested in the BigGAN model trained on the FFHQ dataset that you mentioned in your attachment. I was wondering if it is possible for you to share your trained model with us, as we would like to use it as a benchmark in our experiments. Thank you very much in advance.

**Comment by LukasStruppek** [comment]
Hey,

I just checked—unfortunately, I don't have the weight file anymore. However, we trained in using this repo: https://github.com/ajbrock/BigGAN-PyTorch. You can find all training hyperparameters in Appx. B4 in our paper. One can probably further improve the quality of the generated images by fine-tuning the training hyperparameters.

Best,
Lukas
